
import { User, Notification, DashboardMetric } from "@/types";

// This file contains mock data that will be replaced with Firebase data once connected

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    role: "admin",
    avatar: "https://ui-avatars.com/api/?name=John+Doe&background=random",
    department: "IT",
    position: "System Administrator",
    createdAt: "2023-01-15T08:30:00Z",
    updatedAt: "2023-01-15T08:30:00Z",
    lastActive: "2023-06-01T14:25:00Z",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "manager",
    avatar: "https://ui-avatars.com/api/?name=Jane+Smith&background=random",
    department: "HR",
    position: "HR Manager",
    createdAt: "2023-02-10T10:15:00Z",
    updatedAt: "2023-02-10T10:15:00Z",
    lastActive: "2023-06-02T09:45:00Z",
  },
  {
    id: "3",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    role: "employee",
    avatar: "https://ui-avatars.com/api/?name=Robert+Johnson&background=random",
    department: "Finance",
    position: "Financial Analyst",
    createdAt: "2023-03-05T11:20:00Z",
    updatedAt: "2023-03-05T11:20:00Z",
    lastActive: "2023-06-01T16:30:00Z",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    role: "user",
    avatar: "https://ui-avatars.com/api/?name=Emily+Davis&background=random",
    department: "Marketing",
    position: "Marketing Specialist",
    createdAt: "2023-04-12T09:10:00Z",
    updatedAt: "2023-04-12T09:10:00Z",
    lastActive: "2023-05-30T13:15:00Z",
  },
  {
    id: "5",
    name: "Michael Wilson",
    email: "michael.wilson@example.com",
    role: "employee",
    avatar: "https://ui-avatars.com/api/?name=Michael+Wilson&background=random",
    department: "Operations",
    position: "Operations Manager",
    createdAt: "2023-05-08T14:45:00Z",
    updatedAt: "2023-05-08T14:45:00Z",
    lastActive: "2023-06-02T11:20:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "New User Registered",
    message: "A new user has registered and requires approval.",
    type: "info",
    read: false,
    createdAt: "2023-06-02T08:30:00Z",
    module: "User Management",
    actionUrl: "/users",
  },
  {
    id: "2",
    title: "Ticket Assigned",
    message: "You have been assigned a new support ticket.",
    type: "info",
    read: false,
    createdAt: "2023-06-01T15:45:00Z",
    module: "Help Desk",
    actionUrl: "/helpdesk",
  },
  {
    id: "3",
    title: "Document Approval Required",
    message: "A document requires your approval.",
    type: "warning",
    read: true,
    createdAt: "2023-05-31T11:20:00Z",
    module: "Document Management",
    actionUrl: "/documents",
  },
  {
    id: "4",
    title: "Project Milestone Completed",
    message: "Project Alpha has reached its first milestone.",
    type: "success",
    read: true,
    createdAt: "2023-05-30T16:10:00Z",
    module: "Project Management",
    actionUrl: "/projects",
  },
  {
    id: "5",
    title: "System Maintenance",
    message: "System will be down for maintenance on Saturday, June 10th.",
    type: "error",
    read: false,
    createdAt: "2023-05-29T09:15:00Z",
    module: "Admin",
    actionUrl: "/admin",
  },
];

export const mockDashboardMetrics: DashboardMetric[] = [
  {
    id: "1",
    title: "Total Users",
    value: 254,
    change: 12,
    trend: "up",
    icon: "Users",
    color: "blue",
  },
  {
    id: "2",
    title: "Active Employees",
    value: 186,
    change: 5,
    trend: "up",
    icon: "Briefcase",
    color: "green",
  },
  {
    id: "3",
    title: "Open Tickets",
    value: 42,
    change: 8,
    trend: "down",
    icon: "TicketCheck",
    color: "amber",
  },
  {
    id: "4",
    title: "Documents",
    value: 1254,
    change: 24,
    trend: "up",
    icon: "FileText",
    color: "indigo",
  },
  {
    id: "5",
    title: "Assets",
    value: 872,
    trend: "neutral",
    icon: "Laptop",
    color: "purple",
  },
  {
    id: "6",
    title: "Active Projects",
    value: 36,
    change: 3,
    trend: "up",
    icon: "FolderKanban",
    color: "rose",
  },
];
